# Generated by Django 4.0.2 on 2022-02-03 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapi', '0002_alter_conversation_last_msg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
